name: Deploy Blazor App

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Publish Blazor App
        working-directory: ${{ github.workspace }}
        run: |
         dotnet restore BlazorApp2.sln
         dotnet publish ./BlazorApp2/BlazorApp2/BlazorApp2.csproj -c Release -o ./BlazorApp2/publish

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          echo -e "Host *\n\tStrictHostKeyChecking no\n\tPort 2222\n\t" > ~/.ssh/config

          rsync -avz -e "ssh -i ~/.ssh/deploy_key -p 2222" --delete \
            app/publish/ root@$HOST:/var/www/kymera.cloud

          ssh -i ~/.ssh/deploy_key -p 2222 root@$HOST << 'ENDSSH'
            cd /var/www/kymera.cloud/blazor
            systemctl restart kymera
            sleep 2
            systemctl status kymera
          ENDSSH